services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - "${QDRANT_REST_PORT:-6333}:6333"
      - "${QDRANT_GRPC_PORT:-6334}:6334"
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ${QDRANT_STORAGE_PATH:-./qdrant_data}:/qdrant/storage
    hostname: qdrant
    networks:
      - lia-network
    dns_search: .

  lia-backend:
    build: .
    container_name: lia-backend
    ports:
      - "${HOST_PORT:-3003}:3003"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant
    networks:
      - lia-network

configs:
  qdrant_config:
    content: |
      log_level: ${QDRANT_LOG_LEVEL:-INFO}

networks:
  lia-network:
    driver: bridge